[[mcp_servers]]
name = "laravel-boost"
transport = "stdio"
command = "php"
args = [
    "artisan",
    "boost:mcp",
]

[tools.write_file]
permission = "always"

[tools.edit]
permission = "always"

[tools.bash]
allowlist = [
    "cd",
    "find",
    "git status",
    "head",
    "ls",
    "mkdir",
    "php",
    "vendor/bin/pint",
]
